[package]
name = "photosite-image"
description = "Decoding, scaling and EXIF. Knows of no UI."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
jpeg-decoder.workspace = true
fast_image_resize.workspace = true
image.workspace = true

[dev-dependencies]
tempfile.workspace = true
proptest.workspace = true
